- name: Installing stow
  community.general.homebrew:
    name: stow
    state: present
  tags:
    - install
    - dotfiles
    - stow
- name: Stow dotfiles
  shell: cd $HOME/dotfiles/stow && ./macos
  tags:
    - install
    - dotfiles
    - stow
- name: Unstow dotfiles
  shell: cd $HOME/dotfiles/stow && ./macos-uninstall
  tags:
    - unstow
