- hosts: localhost 
  include_vars: vars/brew-packages.yml
  vars:
    source_key: "../stow/.ssh/id_rsa"
    dest_key: "{{ lookup('env', 'HOME') }}/.ssh/id_rsa"
#  pre_tasks:
#  - name: Update Apt
#    become: true
#    apt:
#      force_apt_get: true
#      update_cache: true
#      state: present
#    tags:
#      - install
#      - core
  tasks:
    - name: SSH
      include_tasks: tasks/ssh.yml
      tags:
        - ssh
    - name: GIT personal
      include_tasks: tasks/git-personal.yml
      tags:
        - git-personal
    - name: Core setup
      include_tasks: tasks/core-setup.yml
      tags:
        - core
# Install omz before stowing dotfiles
    - name: zsh setup
      include_tasks: tasks/oh-my-zsh.yml
      tags:
        - zsh
        - oh-my-zsh
        - install
    - name: stow dotfiles
      include_tasks: tasks/dotfiles.yml
      tags:
        - stow
        - unstow
        - dotfiles
        - install
